server:
  port: 0

eureka:
  client:
    service-url:
      - defaultZone: http://eureka:password@localhost:8761/eureka
spring:
  application:
    name: service-one

openapi:
  service:
    title: Service One #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8080 #api gateway url
springdoc:
  api-docs:
    path: /service-one/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /service-one/swagger-ui.html

logging.level.org.springframework.web: DEBUG